server:
    port: ${SERVER_PORT:8761}
spring:
    application:
        name: ${APPLICATION_NAME:movies-service-registry}
eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:false}
    service-url.defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:     #application is live and database is up
      enabled: true
    readiness-state:            #database is accepting request or not
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

