server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${APPLICATION_NAME:booking-service}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:bookings?createIfNotExist=true}
    username: ${MYSQL_USER:prapti}
    password: ${MYSQL_PASSWORD:prapti21}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:     #application is live and database is up
      enabled: true
    readiness-state:            #database is accepting request or not
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

