server:
   port: ${SERVER_PORT:8082}
spring:
   application:
      name: ${APPLICATION_NAME:payment-service}
   datasource:
      #url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:payments?createIfNotExists=true}
      url: jdbc:mysql://127.0.0.1:3306/payments
      username: ${MYSQL_USER:prapti}
      password: ${MYSQL_PASSWORD:prapti21}
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
   client:
      register-with-eureka: ${REGISTER_WITH_EUREKA:true}
      service-url:
         defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
   endpoints:
      web:
         exposure:
            include: "*"
   health:
      liveness-state: #application is live and database is up
         enabled: true
      readiness-state: #database is accepting request or not
         enabled: true
   endpoint:
      health:
         probes:
            enabled: true

stripe:
   key: sk_test_51OCSJJSBcykHcDLYtD7M5xK2HrDg4RQ2YBkQECNx89tti08WSlvuy5WP9AXfGKLWE7lLs0jMqw5p2gzPOCvx4TpE00yoLjVx1n
